name: CI
on: workflow_call

jobs:
  go-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: '${{ github.workspace }}/go.mod'
          cache: true

      - name: Install go-task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run fmt task
        run: diff -u <(echo -n) <(task fmt)

      - name: Run vet task
        run: task vet

      - name: Run govulncheck task
        run: task govulncheck

      - name: Run test
        run: task test
